# permalink: /blog/:month-:day-:year/:title.html
permalink: /:title

title: zwell 的技术积累
url: https://zwell.github.io/blog
feed: /atom.xml
author_info: <a href="https://zwell.github.io/blog/">zwell</a>
